Name:           ros-melodic-lauv-description
Version:        0.1.6
Release:        0%{?dist}
Summary:        ROS lauv_description package

Group:          Development/Libraries
License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-uuv-assistants
Requires:       ros-melodic-uuv-descriptions
Requires:       ros-melodic-uuv-gazebo-ros-plugins
Requires:       ros-melodic-uuv-sensor-ros-plugins
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-xacro

%description
Robot description files for the LAUV.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Apr 22 2019 Musa Morena Marcusso Manhaes <musa.marcusso@de.bosch.com> - 0.1.6-0
- Autogenerated by Bloom

